name: deploy

on:
  push: 
    branches:
      - main
      - feature/push_images_to_ecr

env:
  AWS_REGION: ap-northest-1
    
jobs:
  deploy:
    name: Deploy app to AWS Fargate
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESSS_KEY_ID }}
          aws-secret-access-key-id: ${{ secrets.PROD_AWS_SECRET_ACCESSS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
